### PR TITLE
Convert PNG icons to SVG

### PR DESCRIPTION
**Pull request by Rainyan**
Converts all of the raster icons (PNG) to vector graphics, for marginally crisper quality due to not needing any resampling when scaling the images (and future-proofing for 4k streaming, I guess :smiley:)

Actual image dimensions for the SVG files should be the same as the PNG ones, although the weapon icons might appear a few px smaller because of the missing downscaling "blur" effect.

Example of an upscaled overlay with the SVG assets:
overlay_hires_example

And a comparison of 250% zoom for PNG vs SVG:
png_vs_svg_scaling_example

### CODE REVIEW

**Comment by Agiel** [comment]
Nice work! Before I merge though, did you verify that the guns' relative sizes look ok when displayed in the overlay (i.e. with height set to 22px)? I know I had to do some tweaks when trimming blank pixels and downscaling the png ones.

Also, just a nitpick but it looks the the MX-S has a scope? ;)

**Comment by Rainyan** [comment]
I _think_ I checked the relative sizes, but I can't remember for sure if I went through all of them. Also, not really sure what happened with the MX scope here, might be some kind of copy paste mistake in the SVG.

I'll push a fix for the phantom scope and confirm the CSS appearance, and report back.

**Comment by Rainyan** [comment]
The incorrect MX scope is now fixed.

I also compared the icon scaling (added `sm_relaydbg_populate` debug server cmd for generating some fake players), and the output looks to be roughly the same. Some of the icons are slightly slimmer.

Previous PNG icons:
PNG_Screenshot_2021-05-12 spec-client

SVG icons:
SVG_Screenshot_2021-05-12 spec-client

Image diff shows some of them are slightly smaller (mainly due to lacking blurred edges). Most notably the ghost is a bit smaller:
diff

I think it looks ok, but perhaps it'd be worth adding some exception for the ghost so it gets a larger icon than the `max-height: 22px`?

**Comment by Rainyan** [comment]
Looking at it again, I think the SVG ghost appears smaller because the PNG version had some cropping going on in the bottom part.

I could do the same cropping for the SVG version, to make it appear larger again?

**Comment by Agiel** [comment]
Yeah I cropped the ghost a bit to make the icon larger, but that was before I moved the ghost icon out of the player panel to make it "pop" more (which is something it seems I've completely forgotten to push to GitHub). So I think this is fine.

I'll merge this and then rebase my stuff on top. Thanks a lot!

**Pull request merged**
